language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - nightly
matrix:
  include:
    - os: windows
      env: JULIA_BSDIFF_LOWMEM=true
      julia: 1.3
    - os: windows
      env: JULIA_BSDIFF_LOWMEM=true
      julia: nightly
notifications:
  email: false
codecov: true
