name = "BSDiff"
uuid = "7b188ff4-8bb6-4dee-bbe1-9b6fdde2c7c5"
authors = ["Stefan Karpinski <stefan@karpinski.org>"]
version = "1.2.0"

[deps]
ArgTools = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
SuffixArrays = "24f65c1e-0a10-5d3d-8a1f-a83399f3fced"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
ArgTools = "1"
BufferedStreams = "1"
CodecBzip2 = "0.6, 0.7"
SuffixArrays = "0.3"
TranscodingStreams = "0.9.5"
julia = "1.3"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
bsdiff_classic_jll = "7424abe3-9926-5da8-9b28-863d6330819c"
bsdiff_endsley_jll = "4b92dbe6-3cad-5173-b451-9946eb17ce71"
zrl_jll = "9fe51eb0-a099-5680-98c2-fe494cf0c162"

[targets]
test = ["Pkg", "Test", "bsdiff_classic_jll", "bsdiff_endsley_jll", "zrl_jll"]
