name = "BSDiff"
uuid = "7b188ff4-8bb6-4dee-bbe1-9b6fdde2c7c5"
authors = ["Stefan Karpinski <stefan@karpinski.org>"]
version = "0.1.0"

[deps]
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
SuffixArrays = "24f65c1e-0a10-5d3d-8a1f-a83399f3fced"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
CodecBzip2 = "0.6"
SuffixArrays = "0.3"
TranscodingStreams = "0.9.5"
julia = "1.3"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
bsdiff_jll = "820cb745-3461-5c14-98e1-21b61faceff9"

[targets]
test = ["Test", "Pkg", "bsdiff_jll"]
