name = "BSDiff"
uuid = "7b188ff4-8bb6-4dee-bbe1-9b6fdde2c7c5"
authors = ["Stefan Karpinski <stefan@karpinski.org>"]
version = "0.1.0"

[deps]
SuffixArrays = "24f65c1e-0a10-5d3d-8a1f-a83399f3fced"

[compat]
SuffixArrays = "0.3"
julia = "1.4"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg"]
